### ISSUE TITLE
Improve QtQmlApplication usage

### ISSUE THREAD

**Issue by approximator** [approximator/Qt-Qbs-Application#10]
https://github.com/approximator/Qt-Qbs-Application/blob/master/examples/SimpleQtQmlApp/SimpleQtQmlApp.qbs#L23

It is looking not as good as it would be:

```
QmlTools.QtQmlApplication {

...

}
```

I think it would be better to use QtQmlApplication as follows:

```
QtQmlApplication {

...

}
```

without **QmlTools.**

**Comment by approximator** [comment]
Maybe we can create **QtQmlApplication.qbs** inside the **imports** directory?

Something like this:

_imports/QtQmlApplication.qbs_

```
QmlTools.QtQmlApplication {

}
```

This will allow using just **QtQmlApplication**

**Comment by AndreyShelest** [comment]
I prefer another case.
import  QmlTools.QtQmlApplication
QmlTools.QtQmlApplication {

}

but in does not work if I choose the same qbs modules structure as in qbs sources. 
for example:
import qbs.FileInfo
....

**Comment by AndreyShelest** [comment]
Already done in https://github.com/approximator/Qt-Qbs-Application/pull/17.
