### ISSUE TITLE
Result of expression 'qmlImportsPaths' [undefined] is not an object.

### ISSUE THREAD

**Issue by approximator** [approximator/Qt-Qbs-Application#8]
When there is no need to import additional qml and qmlImportsPaths is not set, the following error appears:

```
QtQmlApplication.qbs:128: error: Result of expression 'qmlImportsPaths' [undefined] is not an object.
```

**Comment by AndreyShelest** [comment]
Fixed in [https://github.com/approximator/Qt-Qbs-Application/pull/9](url)
